"""empty message

Revision ID: 6b8f7573b5de
Revises: 373dc7870694
Create Date: 2024-02-10 02:16:48.907812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8f7573b5de'
down_revision = '373dc7870694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('discount_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'discounts', ['discount_id'], ['id'])

    # ### end Alembic commands ###
