"""empty message

Revision ID: 70f671534439
Revises: 394f95f47e10
Create Date: 2024-01-26 00:38:46.324965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f671534439'
down_revision = '394f95f47e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_add', sa.String(), nullable=True),
    sa.Column('more_info', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
