"""empty message

Revision ID: 92756ca20ec7
Revises: e5fbe95d6271
Create Date: 2024-02-20 22:30:00.691721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92756ca20ec7'
down_revision = 'e5fbe95d6271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extra_services_car_association',
    sa.Column('ex_service_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['ex_service_id'], ['extra services.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extra_services_car_association')
    # ### end Alembic commands ###
