"""empty message

Revision ID: 99bc0f603bd5
Revises: 92756ca20ec7
Create Date: 2024-02-20 23:13:19.316269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bc0f603bd5'
down_revision = '92756ca20ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra services', schema=None) as batch_op:
        # Dropping a foreign key constraint with the correct name

        # Dropping a column named 'owner_id'
        batch_op.drop_column('owner_id')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###
