"""empty message

Revision ID: e5fbe95d6271
Revises: 70b8a28726bf
Create Date: 2024-02-20 22:11:02.464991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fbe95d6271'
down_revision = '70b8a28726bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extra services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('price_info', sa.Text(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pickup', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drop', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('extras_info', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_orders_customer_id', 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_birthdate')
        batch_op.drop_column('order_owner')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('drop_city')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('pickup_city')
        batch_op.drop_column('customer_phone_op')
        batch_op.drop_column('customer_app')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_app', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('customer_phone_op', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pickup_city', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('drop_city', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('order_owner', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('customer_birthdate', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('extras_info')
        batch_op.drop_column('drop')
        batch_op.drop_column('pickup')
        batch_op.drop_column('customer_id')

    op.drop_table('extra services')
    op.drop_table('customers')
    # ### end Alembic commands ###
